# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a2898d2df27d82ad55a8cc0dd30b45cbcf1a23817fcb934a137e84866e1dff47278bf611a22266db631ae2197f676a72bff423d261650896752f296dab71f4

test:
  secret_key_base: 60544334bf2a944426c0fcfe59c885eeda3aece8b84d01f4fdce1468cffe0e2eb8dc43b311c0f45cbcef5407f3dca99243dffc11a5f5b7c199c5de7fdce2a1ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
